### PR TITLE
v6.0 site style + revise title/banner

### PR DESCRIPTION
**Pull request by vito**
fixes https://github.com/concourse/concourse/issues/5206

Here's how it looks:

image

I took a couple liberties here - feedback welcome! e.g. removing "Concourse" from the banner area and changing the title format to "Resource Types - Concourse CI" to match the rest of the site.

### CODE REVIEW

**Comment by jomsie** [comment]
looks good to me, i like the new bg colour!!

what's the strat for timing? should we push this new banner all at once across the board? when will the main site be updated?

**Comment by jomsie** [comment]
@ibagha there have been some changes to the nav bar / banner, i figure you already know, but ... just in case :)

**Comment by vito** [comment]
@jomsie I think we'll time this around the final v6.0 release, so let's just leave this open 'til then. I'll keep tabs on it for rebases. 👍

**Comment by ibagha** [comment]
Thanks for the update! I've also been wondering, would it make sense to put the 'Resource Types' tab before 'Discuss' and 'Blog'? That way all the resources (docs, examples, project, resource types) are grouped together in the beginning, and the communications pages (blog, discuss) are grouped together at the end. @vito @jomsie

**Comment by vito** [comment]
@ibagha makes sense! i'll update the PR

**Pull request merged**
